version: 1.0.{build}

branches:
  only:
    - master
    - release

max_jobs: 1

environment:
  AHK_PATH: C:\ahk\AutoHotkey.exe
  AHK_DEBUG: true

install:
  - ps: |
      if (!(Test-Path ahk_install.exe)) {
          echo "Downloading AHK installer"
          appveyor DownloadFile https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.30.01/AutoHotkey_1.1.30.01_setup.exe -FileName ahk_install.exe
      } else {
          echo "Using cached installer"
      }
  - ahk_install.exe /S /D=C:\ahk
  - cmd: .\ci\install.bat

build_script:
  - ./bin/build.bat

artifacts:
  - name: dist
    path: dist

cache:
  - ahk_install.exe -> appveyor.yml
